# Netlify build configuration
[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

# Environment variables
[build.environment]
  NODE_VERSION = "20"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
