name: Deploy Backend to Azure App Service

on:
  push:
    branches: [ main ]
    paths:
      - 'Backend/**'
      - 'Backend/requirements.txt'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare deployment package
        run: |
          cp requirements.txt Backend/requirements.txt
          echo "Listing Backend contents after copy:" && ls -la Backend

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: sbi-stock-backend
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./Backend
